apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tekton-chains.yaml

images:
  - name: quay.io/konflux-ci/appstudio-utils
    digest: sha256:366636b0a749700571c862529065b6820b486a770a3b17eaf543e11ac238e837

