apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/enterprise-contract/enterprise-contract-controller/config/crd?ref=e8aeb57b4713b9343901bc99f04800be2589996d
  - ns.yaml
  - public-ecp-rbac.yaml

namespace: enterprise-contract-service

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/enterprise-contract/ec-task-bundle@sha256:07436f0ab151dce35bb0c98dcf75b26a71a5f9b645fe82a14f034a75c17986f5
      - verify_ec_task_git_url=https://github.com/enterprise-contract/ec-cli.git
      - verify_ec_task_git_revision=02ad638e7d8936c59bc4df3b1d0075d4be4ea95a
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml

patches:
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleYAMLSample
      name: ecp-example
    path: remove-ecp-example.yaml
