---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: konflux-builder-bot-actions
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
