---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: konflux-kueue-visibility
  labels:
    rbac.konflux-ci.dev/aggregate-to-viewer: "true"
    rbac.konflux-ci.dev/aggregate-to-contributor: "true"
    rbac.konflux-ci.dev/aggregate-to-maintainer: "true"
    rbac.konflux-ci.dev/aggregate-to-admin: "true"
rules:
  - verbs:
      - get
    apiGroups:
      - visibility.kueue.x-k8s.io
    resources:
      - localqueues/pendingworkloads
