apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: konflux-ui-proxy
  namespace: konflux-ui
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app: proxy
