---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - registry.yaml
  - certificate.yaml
  - trust-bundle.yaml
  - zot-config.yaml

images:
  - name: quay.io/konflux-ci/zot
    newName: quay.io/konflux-ci/zot
    digest: sha256:3bfbfbe5d50c830a2867f5ee68fa190a29af702e4fdcafd7e76b6e2e4f1f1aba
