---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - registry.yaml
  - certificate.yaml
  - trust-bundle.yaml
  - zot-config.yaml

images:
  - name: quay.io/konflux-ci/zot
    newName: quay.io/konflux-ci/zot
    digest: sha256:b81addd8f738c37652910881de8bd0f9cb8a1e821b01e2410f7c781639bbc5b6
