#!/bin/bash
set -euo pipefail

# Generates cert-manager and trust-manager manifests under dependencies/ using Helm.
# Also extracts cert-manager CRDs into operator/test/crds/cert-manager/ for envtest.
# Downloads the prometheus-operator ServiceMonitor CRD into operator/test/crds/prometheus/
# and dependencies/prometheus-operator-crds/.
# Intended for local use and for the Update Third-Party Manifests workflow.
#
# Usage:
#   update-third-party-manifests.sh [REPO_ROOT]
#
# Arguments:
#   REPO_ROOT - Repository root (default: GITHUB_WORKSPACE or git rev-parse --show-toplevel)
#
# Environment:
#   CERT_MANAGER_VERSION          - Required. cert-manager chart version (use vX.Y.Z; from CI or
#                                   eval "$(bash .github/scripts/export-third-party-chart-env.sh)").
#   TRUST_MANAGER_VERSION         - Required. trust-manager chart version (same pattern).
#   PROMETHEUS_OPERATOR_VERSION   - Required. prometheus-operator release tag (e.g. v0.91.0).
#
# Requires: helm, yq, curl on PATH.

REPO_ROOT="${1:-${GITHUB_WORKSPACE:-$(git rev-parse --show-toplevel)}}"
CERT_MANAGER_VERSION="${CERT_MANAGER_VERSION:?CERT_MANAGER_VERSION is required}"
TRUST_MANAGER_VERSION="${TRUST_MANAGER_VERSION:?TRUST_MANAGER_VERSION is required}"
PROMETHEUS_OPERATOR_VERSION="${PROMETHEUS_OPERATOR_VERSION:?PROMETHEUS_OPERATOR_VERSION is required}"

cd "$REPO_ROOT"

if ! command -v helm &>/dev/null; then
  echo "helm is required but not installed" >&2
  exit 1
fi
if ! command -v yq &>/dev/null; then
  echo "yq is required but not installed" >&2
  exit 1
fi
if ! command -v curl &>/dev/null; then
  echo "curl is required but not installed" >&2
  exit 1
fi

# Both charts from https://charts.jetstack.io (same source Renovate tracks)
helm repo add jetstack https://charts.jetstack.io --force-update >/dev/null 2>&1

# cert-manager
helm template cert-manager jetstack/cert-manager \
  --version "$CERT_MANAGER_VERSION" \
  --namespace cert-manager \
  --set installCRDs=true \
  --set 'resources.requests.cpu=90m' \
  --set 'resources.requests.memory=90Mi' \
  --set 'resources.limits.cpu=120m' \
  --set 'resources.limits.memory=120Mi' \
  --set 'webhook.resources.requests.cpu=90m' \
  --set 'webhook.resources.requests.memory=90Mi' \
  --set 'webhook.resources.limits.cpu=120m' \
  --set 'webhook.resources.limits.memory=120Mi' \
  --set 'cainjector.resources.requests.cpu=90m' \
  --set 'cainjector.resources.requests.memory=90Mi' \
  --set 'cainjector.resources.limits.cpu=120m' \
  --set 'cainjector.resources.limits.memory=120Mi' \
  --set 'startupapicheck.resources.requests.cpu=10m' \
  --set 'startupapicheck.resources.limits.memory=64Mi' \
  > dependencies/cert-manager/cert-manager.yaml

# Extract cert-manager CRDs for envtest (only CustomResourceDefinition documents)
CRD_DIR="operator/test/crds/cert-manager"
mkdir -p "$CRD_DIR"
yq 'select(.kind == "CustomResourceDefinition")' dependencies/cert-manager/cert-manager.yaml > "$CRD_DIR/cert-manager.crds.yaml"

# trust-manager
helm template trust-manager jetstack/trust-manager \
  --version "$TRUST_MANAGER_VERSION" \
  --namespace cert-manager \
  --set 'resources.requests.cpu=10m' \
  --set 'resources.requests.memory=50Mi' \
  --set 'resources.limits.cpu=100m' \
  --set 'resources.limits.memory=250Mi' \
  --set 'defaultPackage.resources.requests.cpu=10m' \
  --set 'defaultPackage.resources.requests.memory=50Mi' \
  --set 'defaultPackage.resources.limits.cpu=100m' \
  --set 'defaultPackage.resources.limits.memory=250Mi' \
  > dependencies/trust-manager/trust-manager.yaml

# prometheus-operator ServiceMonitor CRD (Kind envtest + deploy-deps prerequisite)
PROM_TAG="${PROMETHEUS_OPERATOR_VERSION#v}"
PROM_CRD_URL="https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v${PROM_TAG}/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml"
PROM_ENVTEST_CRD="${REPO_ROOT}/operator/test/crds/prometheus/servicemonitors.monitoring.coreos.com.yaml"
PROM_DEPS_CRD="${REPO_ROOT}/dependencies/prometheus-operator-crds/servicemonitors.monitoring.coreos.com.yaml"
mkdir -p "$(dirname "$PROM_ENVTEST_CRD")" "$(dirname "$PROM_DEPS_CRD")"
{
  echo "# Source: prometheus-operator ${PROMETHEUS_OPERATOR_VERSION}"
  echo "# Generated by .github/scripts/update-third-party-manifests.sh — do not edit."
  curl -fsSL "$PROM_CRD_URL"
} > "$PROM_ENVTEST_CRD" || {
  echo "Failed to download ServiceMonitor CRD from ${PROM_CRD_URL}" >&2
  rm -f "$PROM_ENVTEST_CRD"
  exit 1
}
cp -f "$PROM_ENVTEST_CRD" "$PROM_DEPS_CRD"

echo "Generated dependencies/cert-manager/cert-manager.yaml (cert-manager $CERT_MANAGER_VERSION)"
echo "Generated $CRD_DIR/cert-manager.crds.yaml (extracted CRDs for envtest)"
echo "Generated dependencies/trust-manager/trust-manager.yaml (trust-manager $TRUST_MANAGER_VERSION)"
echo "Generated $PROM_ENVTEST_CRD (prometheus-operator ServiceMonitor CRD $PROMETHEUS_OPERATOR_VERSION)"
