#!/usr/bin/env bash
set -euo pipefail

# Extracts the OpenShift CRDs used by operator envtest from the pinned
# github.com/openshift/api Go module (operator/go.mod). Writes curated CRDs to
# operator/test/crds/openshift/.
#
# Only the four CRDs referenced by controller tests are copied (Default
# feature-set variant for clusterversions). Do not load entire
# zz_generated.crd-manifests directories — some OpenShift CRDs exceed CEL cost
# budgets on newer Kubernetes envtest versions.
#
# Usage:
#   update-openshift-test-crds.sh [REPO_ROOT]
#
# Requires: go on PATH.

REPO_ROOT="${1:-${GITHUB_WORKSPACE:-$(git rev-parse --show-toplevel)}}"
REPO_ROOT="$(cd "${REPO_ROOT}" && pwd)"
OPERATOR_DIR="${REPO_ROOT}/operator"
OUT_DIR="${OPERATOR_DIR}/test/crds/openshift"
SCRIPT_NAME=".github/scripts/update-openshift-test-crds.sh"

cd "${OPERATOR_DIR}"

# -mod=mod overrides GOFLAGS=-mod=vendor that may be set in the environment; this repo
# does not vendor Go module sources.
export GOFLAGS="-mod=mod"

# go list -m returns an empty .Dir on cold module caches (e.g. CI runners).
go mod download github.com/openshift/api

read -r OPENSHIFT_API_VERSION OPENSHIFT_API_DIR < <(
  go list -m -f '{{.Version}} {{.Dir}}' github.com/openshift/api
)
if [[ -z "${OPENSHIFT_API_DIR}" ]]; then
  echo "Could not resolve github.com/openshift/api module directory (version ${OPENSHIFT_API_VERSION})" >&2
  exit 1
fi

mkdir -p "${OUT_DIR}"

# dest_filename|relative_source_path_under-module-root
CRDS=(
  "clusterversions.config.openshift.io.yaml|config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-Default.crd.yaml"
  "ingresses.config.openshift.io.yaml|config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_ingresses.crd.yaml"
  "consolelinks.console.openshift.io.yaml|console/v1/zz_generated.crd-manifests/00_consolelinks.crd.yaml"
  "securitycontextconstraints.security.openshift.io.yaml|security/v1/zz_generated.crd-manifests/0000_03_config-operator_01_securitycontextconstraints.crd.yaml"
)

for entry in "${CRDS[@]}"; do
  dest="${entry%%|*}"
  rel_src="${entry#*|}"
  src="${OPENSHIFT_API_DIR}/${rel_src}"
  out="${OUT_DIR}/${dest}"

  if [[ ! -f "${src}" ]]; then
    echo "Missing OpenShift CRD source: ${src}" >&2
    exit 1
  fi

  {
    echo "# Source: github.com/openshift/api ${OPENSHIFT_API_VERSION}"
    echo "# Path:   ${rel_src}"
    echo "# Generated by ${SCRIPT_NAME} — do not edit."
    cat "${src}"
  } > "${out}"

  echo "Generated ${out} (github.com/openshift/api ${OPENSHIFT_API_VERSION})"
done
