apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.authorization.k8s.io_v1_clusterrole_build-service-metrics-reader.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_prometheus-build-service-metrics-reader.yaml
  - monitoring.coreos.com_v1_servicemonitor_build-service.yaml
