//go:build !ignore_autogenerated

/*
Copyright 2025 Konflux CI.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package dex

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connector) DeepCopyInto(out *Connector) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConnectorConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connector.
func (in *Connector) DeepCopy() *Connector {
	if in == nil {
		return nil
	}
	out := new(Connector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorConfig) DeepCopyInto(out *ConnectorConfig) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UserSearch != nil {
		in, out := &in.UserSearch, &out.UserSearch
		*out = new(LDAPUserSearch)
		**out = **in
	}
	if in.GroupSearch != nil {
		in, out := &in.GroupSearch, &out.GroupSearch
		*out = new(LDAPGroupSearch)
		(*in).DeepCopyInto(*out)
	}
	if in.Orgs != nil {
		in, out := &in.Orgs, &out.Orgs
		*out = make([]GitHubOrg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorConfig.
func (in *ConnectorConfig) DeepCopy() *ConnectorConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexParams) DeepCopyInto(out *DexParams) {
	*out = *in
	if in.Connectors != nil {
		in, out := &in.Connectors, &out.Connectors
		*out = make([]Connector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnablePasswordDB != nil {
		in, out := &in.EnablePasswordDB, &out.EnablePasswordDB
		*out = new(bool)
		**out = **in
	}
	if in.StaticPasswords != nil {
		in, out := &in.StaticPasswords, &out.StaticPasswords
		*out = make([]Password, len(*in))
		copy(*out, *in)
	}
	if in.ConfigureLoginWithOpenShift != nil {
		in, out := &in.ConfigureLoginWithOpenShift, &out.ConfigureLoginWithOpenShift
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexParams.
func (in *DexParams) DeepCopy() *DexParams {
	if in == nil {
		return nil
	}
	out := new(DexParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubOrg) DeepCopyInto(out *GitHubOrg) {
	*out = *in
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubOrg.
func (in *GitHubOrg) DeepCopy() *GitHubOrg {
	if in == nil {
		return nil
	}
	out := new(GitHubOrg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPGroupSearch) DeepCopyInto(out *LDAPGroupSearch) {
	*out = *in
	if in.UserMatchers != nil {
		in, out := &in.UserMatchers, &out.UserMatchers
		*out = make([]LDAPUserMatcher, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPGroupSearch.
func (in *LDAPGroupSearch) DeepCopy() *LDAPGroupSearch {
	if in == nil {
		return nil
	}
	out := new(LDAPGroupSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPUserSearch) DeepCopyInto(out *LDAPUserSearch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPUserSearch.
func (in *LDAPUserSearch) DeepCopy() *LDAPUserSearch {
	if in == nil {
		return nil
	}
	out := new(LDAPUserSearch)
	in.DeepCopyInto(out)
	return out
}
