//go:build !ignore_autogenerated

/*
Copyright 2025 Konflux CI.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/konflux-ci/konflux-ci/operator/pkg/dex"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Banner) DeepCopyInto(out *Banner) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = new([]BannerItem)
		if **in != nil {
			in, out := *in, *out
			*out = make([]BannerItem, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Banner.
func (in *Banner) DeepCopy() *Banner {
	if in == nil {
		return nil
	}
	out := new(Banner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BannerItem) DeepCopyInto(out *BannerItem) {
	*out = *in
	if in.Year != nil {
		in, out := &in.Year, &out.Year
		*out = new(int)
		**out = **in
	}
	if in.Month != nil {
		in, out := &in.Month, &out.Month
		*out = new(int)
		**out = **in
	}
	if in.DayOfWeek != nil {
		in, out := &in.DayOfWeek, &out.DayOfWeek
		*out = new(int)
		**out = **in
	}
	if in.DayOfMonth != nil {
		in, out := &in.DayOfMonth, &out.DayOfMonth
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BannerItem.
func (in *BannerItem) DeepCopy() *BannerItem {
	if in == nil {
		return nil
	}
	out := new(BannerItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildServiceConfig) DeepCopyInto(out *BuildServiceConfig) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(KonfluxBuildServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildServiceConfig.
func (in *BuildServiceConfig) DeepCopy() *BuildServiceConfig {
	if in == nil {
		return nil
	}
	out := new(BuildServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerConfig) DeepCopyInto(out *CertManagerConfig) {
	*out = *in
	if in.CreateClusterIssuer != nil {
		in, out := &in.CreateClusterIssuer, &out.CreateClusterIssuer
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerConfig.
func (in *CertManagerConfig) DeepCopy() *CertManagerConfig {
	if in == nil {
		return nil
	}
	out := new(CertManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfig) DeepCopyInto(out *ClusterConfig) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(ClusterConfigData)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfig.
func (in *ClusterConfig) DeepCopy() *ClusterConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfigData) DeepCopyInto(out *ClusterConfigData) {
	*out = *in
	if in.EnableKeylessSigning != nil {
		in, out := &in.EnableKeylessSigning, &out.EnableKeylessSigning
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfigData.
func (in *ClusterConfigData) DeepCopy() *ClusterConfigData {
	if in == nil {
		return nil
	}
	out := new(ClusterConfigData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerSpec) DeepCopyInto(out *ContainerSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerSpec.
func (in *ContainerSpec) DeepCopy() *ContainerSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerManagerDeploymentSpec) DeepCopyInto(out *ControllerManagerDeploymentSpec) {
	*out = *in
	if in.Manager != nil {
		in, out := &in.Manager, &out.Manager
		*out = new(ContainerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerManagerDeploymentSpec.
func (in *ControllerManagerDeploymentSpec) DeepCopy() *ControllerManagerDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ControllerManagerDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultTenantConfig) DeepCopyInto(out *DefaultTenantConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultTenantConfig.
func (in *DefaultTenantConfig) DeepCopy() *DefaultTenantConfig {
	if in == nil {
		return nil
	}
	out := new(DefaultTenantConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexDeploymentSpec) DeepCopyInto(out *DexDeploymentSpec) {
	*out = *in
	if in.Dex != nil {
		in, out := &in.Dex, &out.Dex
		*out = new(ContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(dex.DexParams)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexDeploymentSpec.
func (in *DexDeploymentSpec) DeepCopy() *DexDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DexDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubIntegration) DeepCopyInto(out *GitHubIntegration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubIntegration.
func (in *GitHubIntegration) DeepCopy() *GitHubIntegration {
	if in == nil {
		return nil
	}
	out := new(GitHubIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageControllerConfig) DeepCopyInto(out *ImageControllerConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageControllerConfig.
func (in *ImageControllerConfig) DeepCopy() *ImageControllerConfig {
	if in == nil {
		return nil
	}
	out := new(ImageControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfoImageControllerConfig) DeepCopyInto(out *InfoImageControllerConfig) {
	*out = *in
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]InfoNotificationConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfoImageControllerConfig.
func (in *InfoImageControllerConfig) DeepCopy() *InfoImageControllerConfig {
	if in == nil {
		return nil
	}
	out := new(InfoImageControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfoNotificationConfig) DeepCopyInto(out *InfoNotificationConfig) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfoNotificationConfig.
func (in *InfoNotificationConfig) DeepCopy() *InfoNotificationConfig {
	if in == nil {
		return nil
	}
	out := new(InfoNotificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IngressClassName != nil {
		in, out := &in.IngressClassName, &out.IngressClassName
		*out = new(string)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodePortService != nil {
		in, out := &in.NodePortService, &out.NodePortService
		*out = new(NodePortServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressStatus) DeepCopyInto(out *IngressStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressStatus.
func (in *IngressStatus) DeepCopy() *IngressStatus {
	if in == nil {
		return nil
	}
	out := new(IngressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationServiceConfig) DeepCopyInto(out *IntegrationServiceConfig) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(KonfluxIntegrationServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationServiceConfig.
func (in *IntegrationServiceConfig) DeepCopy() *IntegrationServiceConfig {
	if in == nil {
		return nil
	}
	out := new(IntegrationServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationsConfig) DeepCopyInto(out *IntegrationsConfig) {
	*out = *in
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubIntegration)
		**out = **in
	}
	if in.SBOMServer != nil {
		in, out := &in.SBOMServer, &out.SBOMServer
		*out = new(SBOMServerConfig)
		**out = **in
	}
	if in.ImageController != nil {
		in, out := &in.ImageController, &out.ImageController
		*out = new(InfoImageControllerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationsConfig.
func (in *IntegrationsConfig) DeepCopy() *IntegrationsConfig {
	if in == nil {
		return nil
	}
	out := new(IntegrationsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalRegistryConfig) DeepCopyInto(out *InternalRegistryConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalRegistryConfig.
func (in *InternalRegistryConfig) DeepCopy() *InternalRegistryConfig {
	if in == nil {
		return nil
	}
	out := new(InternalRegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Konflux) DeepCopyInto(out *Konflux) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Konflux.
func (in *Konflux) DeepCopy() *Konflux {
	if in == nil {
		return nil
	}
	out := new(Konflux)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Konflux) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxApplicationAPI) DeepCopyInto(out *KonfluxApplicationAPI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxApplicationAPI.
func (in *KonfluxApplicationAPI) DeepCopy() *KonfluxApplicationAPI {
	if in == nil {
		return nil
	}
	out := new(KonfluxApplicationAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxApplicationAPI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxApplicationAPIList) DeepCopyInto(out *KonfluxApplicationAPIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxApplicationAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxApplicationAPIList.
func (in *KonfluxApplicationAPIList) DeepCopy() *KonfluxApplicationAPIList {
	if in == nil {
		return nil
	}
	out := new(KonfluxApplicationAPIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxApplicationAPIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxApplicationAPISpec) DeepCopyInto(out *KonfluxApplicationAPISpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxApplicationAPISpec.
func (in *KonfluxApplicationAPISpec) DeepCopy() *KonfluxApplicationAPISpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxApplicationAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxApplicationAPIStatus) DeepCopyInto(out *KonfluxApplicationAPIStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxApplicationAPIStatus.
func (in *KonfluxApplicationAPIStatus) DeepCopy() *KonfluxApplicationAPIStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxApplicationAPIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxBuildService) DeepCopyInto(out *KonfluxBuildService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxBuildService.
func (in *KonfluxBuildService) DeepCopy() *KonfluxBuildService {
	if in == nil {
		return nil
	}
	out := new(KonfluxBuildService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxBuildService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxBuildServiceList) DeepCopyInto(out *KonfluxBuildServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxBuildService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxBuildServiceList.
func (in *KonfluxBuildServiceList) DeepCopy() *KonfluxBuildServiceList {
	if in == nil {
		return nil
	}
	out := new(KonfluxBuildServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxBuildServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxBuildServiceSpec) DeepCopyInto(out *KonfluxBuildServiceSpec) {
	*out = *in
	if in.BuildControllerManager != nil {
		in, out := &in.BuildControllerManager, &out.BuildControllerManager
		*out = new(ControllerManagerDeploymentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PipelineConfig != nil {
		in, out := &in.PipelineConfig, &out.PipelineConfig
		*out = new(PipelineConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxBuildServiceSpec.
func (in *KonfluxBuildServiceSpec) DeepCopy() *KonfluxBuildServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxBuildServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxBuildServiceStatus) DeepCopyInto(out *KonfluxBuildServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxBuildServiceStatus.
func (in *KonfluxBuildServiceStatus) DeepCopy() *KonfluxBuildServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxBuildServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxCertManager) DeepCopyInto(out *KonfluxCertManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxCertManager.
func (in *KonfluxCertManager) DeepCopy() *KonfluxCertManager {
	if in == nil {
		return nil
	}
	out := new(KonfluxCertManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxCertManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxCertManagerList) DeepCopyInto(out *KonfluxCertManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxCertManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxCertManagerList.
func (in *KonfluxCertManagerList) DeepCopy() *KonfluxCertManagerList {
	if in == nil {
		return nil
	}
	out := new(KonfluxCertManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxCertManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxCertManagerSpec) DeepCopyInto(out *KonfluxCertManagerSpec) {
	*out = *in
	if in.CreateClusterIssuer != nil {
		in, out := &in.CreateClusterIssuer, &out.CreateClusterIssuer
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxCertManagerSpec.
func (in *KonfluxCertManagerSpec) DeepCopy() *KonfluxCertManagerSpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxCertManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxCertManagerStatus) DeepCopyInto(out *KonfluxCertManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxCertManagerStatus.
func (in *KonfluxCertManagerStatus) DeepCopy() *KonfluxCertManagerStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxCertManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxDefaultTenant) DeepCopyInto(out *KonfluxDefaultTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxDefaultTenant.
func (in *KonfluxDefaultTenant) DeepCopy() *KonfluxDefaultTenant {
	if in == nil {
		return nil
	}
	out := new(KonfluxDefaultTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxDefaultTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxDefaultTenantList) DeepCopyInto(out *KonfluxDefaultTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxDefaultTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxDefaultTenantList.
func (in *KonfluxDefaultTenantList) DeepCopy() *KonfluxDefaultTenantList {
	if in == nil {
		return nil
	}
	out := new(KonfluxDefaultTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxDefaultTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxDefaultTenantSpec) DeepCopyInto(out *KonfluxDefaultTenantSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxDefaultTenantSpec.
func (in *KonfluxDefaultTenantSpec) DeepCopy() *KonfluxDefaultTenantSpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxDefaultTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxDefaultTenantStatus) DeepCopyInto(out *KonfluxDefaultTenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxDefaultTenantStatus.
func (in *KonfluxDefaultTenantStatus) DeepCopy() *KonfluxDefaultTenantStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxDefaultTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxEnterpriseContract) DeepCopyInto(out *KonfluxEnterpriseContract) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxEnterpriseContract.
func (in *KonfluxEnterpriseContract) DeepCopy() *KonfluxEnterpriseContract {
	if in == nil {
		return nil
	}
	out := new(KonfluxEnterpriseContract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxEnterpriseContract) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxEnterpriseContractList) DeepCopyInto(out *KonfluxEnterpriseContractList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxEnterpriseContract, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxEnterpriseContractList.
func (in *KonfluxEnterpriseContractList) DeepCopy() *KonfluxEnterpriseContractList {
	if in == nil {
		return nil
	}
	out := new(KonfluxEnterpriseContractList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxEnterpriseContractList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxEnterpriseContractSpec) DeepCopyInto(out *KonfluxEnterpriseContractSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxEnterpriseContractSpec.
func (in *KonfluxEnterpriseContractSpec) DeepCopy() *KonfluxEnterpriseContractSpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxEnterpriseContractSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxEnterpriseContractStatus) DeepCopyInto(out *KonfluxEnterpriseContractStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxEnterpriseContractStatus.
func (in *KonfluxEnterpriseContractStatus) DeepCopy() *KonfluxEnterpriseContractStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxEnterpriseContractStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxImageController) DeepCopyInto(out *KonfluxImageController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxImageController.
func (in *KonfluxImageController) DeepCopy() *KonfluxImageController {
	if in == nil {
		return nil
	}
	out := new(KonfluxImageController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxImageController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxImageControllerList) DeepCopyInto(out *KonfluxImageControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxImageController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxImageControllerList.
func (in *KonfluxImageControllerList) DeepCopy() *KonfluxImageControllerList {
	if in == nil {
		return nil
	}
	out := new(KonfluxImageControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxImageControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxImageControllerSpec) DeepCopyInto(out *KonfluxImageControllerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxImageControllerSpec.
func (in *KonfluxImageControllerSpec) DeepCopy() *KonfluxImageControllerSpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxImageControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxImageControllerStatus) DeepCopyInto(out *KonfluxImageControllerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxImageControllerStatus.
func (in *KonfluxImageControllerStatus) DeepCopy() *KonfluxImageControllerStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxImageControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxInfo) DeepCopyInto(out *KonfluxInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxInfo.
func (in *KonfluxInfo) DeepCopy() *KonfluxInfo {
	if in == nil {
		return nil
	}
	out := new(KonfluxInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxInfoConfig) DeepCopyInto(out *KonfluxInfoConfig) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(KonfluxInfoSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxInfoConfig.
func (in *KonfluxInfoConfig) DeepCopy() *KonfluxInfoConfig {
	if in == nil {
		return nil
	}
	out := new(KonfluxInfoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxInfoList) DeepCopyInto(out *KonfluxInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxInfoList.
func (in *KonfluxInfoList) DeepCopy() *KonfluxInfoList {
	if in == nil {
		return nil
	}
	out := new(KonfluxInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxInfoSpec) DeepCopyInto(out *KonfluxInfoSpec) {
	*out = *in
	if in.PublicInfo != nil {
		in, out := &in.PublicInfo, &out.PublicInfo
		*out = new(PublicInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Banner != nil {
		in, out := &in.Banner, &out.Banner
		*out = new(Banner)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterConfig != nil {
		in, out := &in.ClusterConfig, &out.ClusterConfig
		*out = new(ClusterConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxInfoSpec.
func (in *KonfluxInfoSpec) DeepCopy() *KonfluxInfoSpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxInfoStatus) DeepCopyInto(out *KonfluxInfoStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxInfoStatus.
func (in *KonfluxInfoStatus) DeepCopy() *KonfluxInfoStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxIntegrationService) DeepCopyInto(out *KonfluxIntegrationService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxIntegrationService.
func (in *KonfluxIntegrationService) DeepCopy() *KonfluxIntegrationService {
	if in == nil {
		return nil
	}
	out := new(KonfluxIntegrationService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxIntegrationService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxIntegrationServiceList) DeepCopyInto(out *KonfluxIntegrationServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxIntegrationService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxIntegrationServiceList.
func (in *KonfluxIntegrationServiceList) DeepCopy() *KonfluxIntegrationServiceList {
	if in == nil {
		return nil
	}
	out := new(KonfluxIntegrationServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxIntegrationServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxIntegrationServiceSpec) DeepCopyInto(out *KonfluxIntegrationServiceSpec) {
	*out = *in
	if in.IntegrationControllerManager != nil {
		in, out := &in.IntegrationControllerManager, &out.IntegrationControllerManager
		*out = new(ControllerManagerDeploymentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxIntegrationServiceSpec.
func (in *KonfluxIntegrationServiceSpec) DeepCopy() *KonfluxIntegrationServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxIntegrationServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxIntegrationServiceStatus) DeepCopyInto(out *KonfluxIntegrationServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxIntegrationServiceStatus.
func (in *KonfluxIntegrationServiceStatus) DeepCopy() *KonfluxIntegrationServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxIntegrationServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxInternalRegistry) DeepCopyInto(out *KonfluxInternalRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxInternalRegistry.
func (in *KonfluxInternalRegistry) DeepCopy() *KonfluxInternalRegistry {
	if in == nil {
		return nil
	}
	out := new(KonfluxInternalRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxInternalRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxInternalRegistryList) DeepCopyInto(out *KonfluxInternalRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxInternalRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxInternalRegistryList.
func (in *KonfluxInternalRegistryList) DeepCopy() *KonfluxInternalRegistryList {
	if in == nil {
		return nil
	}
	out := new(KonfluxInternalRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxInternalRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxInternalRegistrySpec) DeepCopyInto(out *KonfluxInternalRegistrySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxInternalRegistrySpec.
func (in *KonfluxInternalRegistrySpec) DeepCopy() *KonfluxInternalRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxInternalRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxInternalRegistryStatus) DeepCopyInto(out *KonfluxInternalRegistryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxInternalRegistryStatus.
func (in *KonfluxInternalRegistryStatus) DeepCopy() *KonfluxInternalRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxInternalRegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxList) DeepCopyInto(out *KonfluxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Konflux, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxList.
func (in *KonfluxList) DeepCopy() *KonfluxList {
	if in == nil {
		return nil
	}
	out := new(KonfluxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxNamespaceLister) DeepCopyInto(out *KonfluxNamespaceLister) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxNamespaceLister.
func (in *KonfluxNamespaceLister) DeepCopy() *KonfluxNamespaceLister {
	if in == nil {
		return nil
	}
	out := new(KonfluxNamespaceLister)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxNamespaceLister) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxNamespaceListerList) DeepCopyInto(out *KonfluxNamespaceListerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxNamespaceLister, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxNamespaceListerList.
func (in *KonfluxNamespaceListerList) DeepCopy() *KonfluxNamespaceListerList {
	if in == nil {
		return nil
	}
	out := new(KonfluxNamespaceListerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxNamespaceListerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxNamespaceListerSpec) DeepCopyInto(out *KonfluxNamespaceListerSpec) {
	*out = *in
	if in.NamespaceLister != nil {
		in, out := &in.NamespaceLister, &out.NamespaceLister
		*out = new(NamespaceListerDeploymentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxNamespaceListerSpec.
func (in *KonfluxNamespaceListerSpec) DeepCopy() *KonfluxNamespaceListerSpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxNamespaceListerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxNamespaceListerStatus) DeepCopyInto(out *KonfluxNamespaceListerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxNamespaceListerStatus.
func (in *KonfluxNamespaceListerStatus) DeepCopy() *KonfluxNamespaceListerStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxNamespaceListerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxRBAC) DeepCopyInto(out *KonfluxRBAC) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxRBAC.
func (in *KonfluxRBAC) DeepCopy() *KonfluxRBAC {
	if in == nil {
		return nil
	}
	out := new(KonfluxRBAC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxRBAC) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxRBACList) DeepCopyInto(out *KonfluxRBACList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxRBAC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxRBACList.
func (in *KonfluxRBACList) DeepCopy() *KonfluxRBACList {
	if in == nil {
		return nil
	}
	out := new(KonfluxRBACList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxRBACList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxRBACSpec) DeepCopyInto(out *KonfluxRBACSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxRBACSpec.
func (in *KonfluxRBACSpec) DeepCopy() *KonfluxRBACSpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxRBACSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxRBACStatus) DeepCopyInto(out *KonfluxRBACStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxRBACStatus.
func (in *KonfluxRBACStatus) DeepCopy() *KonfluxRBACStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxRBACStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxReleaseService) DeepCopyInto(out *KonfluxReleaseService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxReleaseService.
func (in *KonfluxReleaseService) DeepCopy() *KonfluxReleaseService {
	if in == nil {
		return nil
	}
	out := new(KonfluxReleaseService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxReleaseService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxReleaseServiceList) DeepCopyInto(out *KonfluxReleaseServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxReleaseService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxReleaseServiceList.
func (in *KonfluxReleaseServiceList) DeepCopy() *KonfluxReleaseServiceList {
	if in == nil {
		return nil
	}
	out := new(KonfluxReleaseServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxReleaseServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxReleaseServiceSpec) DeepCopyInto(out *KonfluxReleaseServiceSpec) {
	*out = *in
	if in.ReleaseControllerManager != nil {
		in, out := &in.ReleaseControllerManager, &out.ReleaseControllerManager
		*out = new(ControllerManagerDeploymentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxReleaseServiceSpec.
func (in *KonfluxReleaseServiceSpec) DeepCopy() *KonfluxReleaseServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxReleaseServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxReleaseServiceStatus) DeepCopyInto(out *KonfluxReleaseServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxReleaseServiceStatus.
func (in *KonfluxReleaseServiceStatus) DeepCopy() *KonfluxReleaseServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxReleaseServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxSpec) DeepCopyInto(out *KonfluxSpec) {
	*out = *in
	if in.ImageController != nil {
		in, out := &in.ImageController, &out.ImageController
		*out = new(ImageControllerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KonfluxUI != nil {
		in, out := &in.KonfluxUI, &out.KonfluxUI
		*out = new(KonfluxUIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KonfluxIntegrationService != nil {
		in, out := &in.KonfluxIntegrationService, &out.KonfluxIntegrationService
		*out = new(IntegrationServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KonfluxReleaseService != nil {
		in, out := &in.KonfluxReleaseService, &out.KonfluxReleaseService
		*out = new(ReleaseServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KonfluxBuildService != nil {
		in, out := &in.KonfluxBuildService, &out.KonfluxBuildService
		*out = new(BuildServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceLister != nil {
		in, out := &in.NamespaceLister, &out.NamespaceLister
		*out = new(NamespaceListerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KonfluxInfo != nil {
		in, out := &in.KonfluxInfo, &out.KonfluxInfo
		*out = new(KonfluxInfoConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalRegistry != nil {
		in, out := &in.InternalRegistry, &out.InternalRegistry
		*out = new(InternalRegistryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultTenant != nil {
		in, out := &in.DefaultTenant, &out.DefaultTenant
		*out = new(DefaultTenantConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxSpec.
func (in *KonfluxSpec) DeepCopy() *KonfluxSpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxStatus) DeepCopyInto(out *KonfluxStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ComponentStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxStatus.
func (in *KonfluxStatus) DeepCopy() *KonfluxStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxUI) DeepCopyInto(out *KonfluxUI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxUI.
func (in *KonfluxUI) DeepCopy() *KonfluxUI {
	if in == nil {
		return nil
	}
	out := new(KonfluxUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxUI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxUIConfig) DeepCopyInto(out *KonfluxUIConfig) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(KonfluxUISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxUIConfig.
func (in *KonfluxUIConfig) DeepCopy() *KonfluxUIConfig {
	if in == nil {
		return nil
	}
	out := new(KonfluxUIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxUIList) DeepCopyInto(out *KonfluxUIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KonfluxUI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxUIList.
func (in *KonfluxUIList) DeepCopy() *KonfluxUIList {
	if in == nil {
		return nil
	}
	out := new(KonfluxUIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KonfluxUIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxUISpec) DeepCopyInto(out *KonfluxUISpec) {
	*out = *in
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ProxyDeploymentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Dex != nil {
		in, out := &in.Dex, &out.Dex
		*out = new(DexDeploymentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxUISpec.
func (in *KonfluxUISpec) DeepCopy() *KonfluxUISpec {
	if in == nil {
		return nil
	}
	out := new(KonfluxUISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KonfluxUIStatus) DeepCopyInto(out *KonfluxUIStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KonfluxUIStatus.
func (in *KonfluxUIStatus) DeepCopy() *KonfluxUIStatus {
	if in == nil {
		return nil
	}
	out := new(KonfluxUIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceListerConfig) DeepCopyInto(out *NamespaceListerConfig) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(KonfluxNamespaceListerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceListerConfig.
func (in *NamespaceListerConfig) DeepCopy() *NamespaceListerConfig {
	if in == nil {
		return nil
	}
	out := new(NamespaceListerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceListerDeploymentSpec) DeepCopyInto(out *NamespaceListerDeploymentSpec) {
	*out = *in
	if in.NamespaceLister != nil {
		in, out := &in.NamespaceLister, &out.NamespaceLister
		*out = new(ContainerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceListerDeploymentSpec.
func (in *NamespaceListerDeploymentSpec) DeepCopy() *NamespaceListerDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceListerDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePortServiceSpec) DeepCopyInto(out *NodePortServiceSpec) {
	*out = *in
	if in.HTTPSPort != nil {
		in, out := &in.HTTPSPort, &out.HTTPSPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePortServiceSpec.
func (in *NodePortServiceSpec) DeepCopy() *NodePortServiceSpec {
	if in == nil {
		return nil
	}
	out := new(NodePortServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineConfigSpec) DeepCopyInto(out *PipelineConfigSpec) {
	*out = *in
	if in.Pipelines != nil {
		in, out := &in.Pipelines, &out.Pipelines
		*out = make([]PipelineSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineConfigSpec.
func (in *PipelineConfigSpec) DeepCopy() *PipelineConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSpec) DeepCopyInto(out *PipelineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSpec.
func (in *PipelineSpec) DeepCopy() *PipelineSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyDeploymentSpec) DeepCopyInto(out *ProxyDeploymentSpec) {
	*out = *in
	if in.Nginx != nil {
		in, out := &in.Nginx, &out.Nginx
		*out = new(ContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OAuth2Proxy != nil {
		in, out := &in.OAuth2Proxy, &out.OAuth2Proxy
		*out = new(ContainerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyDeploymentSpec.
func (in *ProxyDeploymentSpec) DeepCopy() *ProxyDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicInfo) DeepCopyInto(out *PublicInfo) {
	*out = *in
	if in.Integrations != nil {
		in, out := &in.Integrations, &out.Integrations
		*out = new(IntegrationsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RBAC != nil {
		in, out := &in.RBAC, &out.RBAC
		*out = make([]RBACRole, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicInfo.
func (in *PublicInfo) DeepCopy() *PublicInfo {
	if in == nil {
		return nil
	}
	out := new(PublicInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACRole) DeepCopyInto(out *RBACRole) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACRole.
func (in *RBACRole) DeepCopy() *RBACRole {
	if in == nil {
		return nil
	}
	out := new(RBACRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseServiceConfig) DeepCopyInto(out *ReleaseServiceConfig) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(KonfluxReleaseServiceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseServiceConfig.
func (in *ReleaseServiceConfig) DeepCopy() *ReleaseServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ReleaseServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SBOMServerConfig) DeepCopyInto(out *SBOMServerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SBOMServerConfig.
func (in *SBOMServerConfig) DeepCopy() *SBOMServerConfig {
	if in == nil {
		return nil
	}
	out := new(SBOMServerConfig)
	in.DeepCopyInto(out)
	return out
}
