apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: redhat-trusted-tasks
  namespace: enterprise-contract-service
spec:
  description: Rules used to verify Tekton Task definitions comply to Red Hat's standards.
  name: Red Hat Trusted Tasks
  sources:
  - config:
      exclude: []
      include:
      - kind
    data:
    - github.com/release-engineering/rhtap-ec-policy.git//data?ref=dd1a3dd1bf2299e1da9936b89e7279b6ab443bec
    name: Default
    policy:
    - oci::quay.io/conforma/task-policy:konflux@sha256:d653a9e8c2280556561dfea239190f56e6d4b34a0a2ae7fda58fd2221abaeb77
