apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: redhat-trusted-tasks
  namespace: enterprise-contract-service
spec:
  description: Rules used to verify Tekton Task definitions comply to Red Hat's standards.
  name: Red Hat Trusted Tasks
  sources:
  - config:
      exclude: []
      include:
      - kind
    data:
    - github.com/release-engineering/rhtap-ec-policy//data
    name: Default
    policy:
    - oci::quay.io/conforma/task-policy:konflux@sha256:a90d6458b158b253604695a15e403e33c1e225f93b4814754c8e39228f781e77
