apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - Caddyfile
  name: proxy-caddyfile
- files:
  - tekton-results.caddy
  - kite.caddy
  - kubearchive.caddy
  - watson.caddy
  name: proxy-caddy-templates
- files:
  - generate-proxy-config.sh
  name: proxy-generate-config
images:
- digest: sha256:3b38c3559a04477a9cff0c51beb54ae1df7a9f3a21426be7523adc16a7b4b724
  name: quay.io/konflux-ci/konflux-ui
  newName: quay.io/konflux-ci/konflux-ui
- digest: sha256:056d331dfeb05e8ae54a1fb97d83250762a045b22e5198c7188d3f018a4cce85
  name: quay.io/konflux-ci/oauth2-proxy
  newName: quay.io/konflux-ci/oauth2-proxy
- digest: sha256:1131cd361cf72e6a4350b039018c0317a012ff0291af36a6944ddfda7570df69
  name: quay.io/konflux-ci/reverse-proxy
  newName: quay.io/konflux-ci/reverse-proxy
kind: Kustomization
namespace: konflux-ui
resources:
- proxy.yaml
- rbac.yaml
