apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - Caddyfile
  name: proxy-caddyfile
- files:
  - tekton-results.caddy
  - kite.caddy
  - kubearchive.caddy
  - watson.caddy
  name: proxy-caddy-templates
- files:
  - generate-proxy-config.sh
  name: proxy-generate-config
images:
- digest: sha256:5730bfed253a4e7b33226c05195166f0adde81020df7bfbb7edd42376bf818ad
  name: quay.io/konflux-ci/konflux-ui
  newName: quay.io/konflux-ci/konflux-ui
- digest: sha256:c6acbe90b688cf2a6f3ce28cb9f9022f82bc55ba7b49224c1c26f2a81cea5e90
  name: quay.io/konflux-ci/oauth2-proxy
  newName: quay.io/konflux-ci/oauth2-proxy
- digest: sha256:d0b9faf5b3cd15c818d6035ba8fc981ff73197b2375597861904c5af21d71a38
  name: quay.io/konflux-ci/reverse-proxy
  newName: quay.io/konflux-ci/reverse-proxy
kind: Kustomization
namespace: konflux-ui
resources:
- proxy.yaml
- rbac.yaml
