apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - Caddyfile
  name: proxy-caddyfile
- files:
  - tekton-results.caddy
  - kite.caddy
  - kubearchive.caddy
  - watson.caddy
  name: proxy-caddy-templates
- files:
  - generate-proxy-config.sh
  name: proxy-generate-config
images:
- digest: sha256:a223e494cdc88b1c7ba452508082e5960e9ecdd7ae6463affce98b4e78960899
  name: quay.io/konflux-ci/konflux-ui
  newName: quay.io/konflux-ci/konflux-ui
- digest: sha256:4169ca2a51cab4e72069348f7dcd280e5b3d051ae25b2f5bda14dd78e7d0ab4d
  name: registry.access.redhat.com/hi/oauth2-proxy
  newName: registry.access.redhat.com/hi/oauth2-proxy
- digest: sha256:03420262b90bb33f575cd9c77e08e41452b220d054dfe472fff900094e953076
  name: quay.io/konflux-ci/reverse-proxy
  newName: quay.io/konflux-ci/reverse-proxy
kind: Kustomization
namespace: konflux-ui
resources:
- proxy.yaml
- rbac.yaml
