apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-services/config/crd?ref=c24151791e9c177b20213488e119d6e94ad75d9d

namespace: release-service
