apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-services/config/crd?ref=f88246d39dd900418cb4dc015dadc8414aca4911

namespace: release-service
