/*
Copyright 2025 Konflux CI.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package defaulttenant

import (
	"context"
	"fmt"
	"time"

	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/builder"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	crpredicate "sigs.k8s.io/controller-runtime/pkg/predicate"

	konfluxv1alpha1 "github.com/konflux-ci/konflux-ci/operator/api/v1alpha1"
	"github.com/konflux-ci/konflux-ci/operator/internal/condition"
	"github.com/konflux-ci/konflux-ci/operator/internal/constant"
	"github.com/konflux-ci/konflux-ci/operator/internal/controller/internalregistry"
	"github.com/konflux-ci/konflux-ci/operator/internal/predicate"
	"github.com/konflux-ci/konflux-ci/operator/pkg/manifests"
	"github.com/konflux-ci/konflux-ci/operator/pkg/serviceaccount"
	"github.com/konflux-ci/konflux-ci/operator/pkg/tracking"
)

const (
	// CRName is the singleton name for the KonfluxDefaultTenant CR.
	CRName = "konflux-default-tenant"
	// DefaultTenantNamespace is the namespace created by this controller.
	DefaultTenantNamespace = "default-tenant"
	// RegistryCredentialsSecretName is the default secret name used for registry auth in default-tenant.
	RegistryCredentialsSecretName = "regcred-internal-registry" //nolint:gosec // secret name, not a credential
	// RegistrySourceSecretNamespace is the namespace holding internal registry client credentials.
	RegistrySourceSecretNamespace = internalregistry.RegistryNamespace
	// RegistrySourceSecretName is the source secret generated by the internal registry reconciler.
	RegistrySourceSecretName = internalregistry.ClientCredentialsSecretName
	// IntegrationRunnerServiceAccountName is the SA used by integration / Conforma PipelineRuns.
	IntegrationRunnerServiceAccountName = "konflux-integration-runner"
	// FieldManager is the field manager identifier for server-side apply.
	FieldManager = "konflux-defaulttenant-controller"
	// crKind is used in error messages to identify this CR type.
	crKind = "KonfluxDefaultTenant"
)

// DefaultTenantCleanupGVKs defines which resource types should be cleaned up when they are
// no longer part of the desired state.
var DefaultTenantCleanupGVKs = []schema.GroupVersionKind{
	{Group: "", Version: "v1", Kind: "Secret"},
}

// DefaultTenantClusterScopedAllowList restricts which cluster-scoped resources can be deleted
// during orphan cleanup.
var DefaultTenantClusterScopedAllowList tracking.ClusterScopedAllowList = nil

// KonfluxDefaultTenantReconciler reconciles a KonfluxDefaultTenant object
type KonfluxDefaultTenantReconciler struct {
	client.Client
	Scheme      *runtime.Scheme
	ObjectStore *manifests.ObjectStore
}

// +kubebuilder:rbac:groups=konflux.konflux-ci.dev,resources=konfluxdefaulttenants,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=konflux.konflux-ci.dev,resources=konfluxdefaulttenants/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=konflux.konflux-ci.dev,resources=konfluxdefaulttenants/finalizers,verbs=update
// +kubebuilder:rbac:groups=konflux.konflux-ci.dev,resources=konfluxinternalregistries,verbs=get;list;watch
// +kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups="",resources=serviceaccounts,verbs=create;get;list;patch;watch

// RBAC permissions required to create RoleBindings that reference these ClusterRoles.
// The bind verb allows creating bindings without needing all the underlying permissions.
// +kubebuilder:rbac:groups=rbac.authorization.k8s.io,resources=clusterroles,resourceNames=konflux-maintainer-user-actions,verbs=bind
// +kubebuilder:rbac:groups=rbac.authorization.k8s.io,resources=clusterroles,resourceNames=konflux-integration-runner,verbs=bind

// Reconcile is part of the main kubernetes reconciliation loop which aims to
// move the current state of the cluster closer to the desired state.
//
// For more details, check Reconcile and its Result here:
// - https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.21.0/pkg/reconcile
func (r *KonfluxDefaultTenantReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := logf.FromContext(ctx)

	// Fetch the KonfluxDefaultTenant instance
	defaultTenant := &konfluxv1alpha1.KonfluxDefaultTenant{}
	if err := r.Get(ctx, req.NamespacedName, defaultTenant); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	log.Info("Reconciling KonfluxDefaultTenant", "name", defaultTenant.Name)

	// Create error handler for consistent error reporting
	errHandler := condition.NewReconcileErrorHandler(log, r.Status(), defaultTenant, crKind)

	// Create a tracking client with ownership config for this reconcile.
	tc := tracking.NewClientWithOwnership(r.Client, tracking.OwnershipConfig{
		Owner:             defaultTenant,
		OwnerLabelKey:     constant.KonfluxOwnerLabel,
		ComponentLabelKey: constant.KonfluxComponentLabel,
		Component:         string(manifests.DefaultTenant),
		FieldManager:      FieldManager,
	})

	registryPresent, err := r.internalRegistryCRExists(ctx)
	if err != nil {
		return errHandler.HandleApplyError(ctx, err)
	}

	// Apply all embedded manifests (integration-runner registry cred refs are merged into the SA
	// object in-memory when the internal registry CR exists, so one SSA apply reaches full state).
	if err := r.applyManifests(ctx, tc, registryPresent); err != nil {
		return errHandler.HandleApplyError(ctx, err)
	}

	if !registryPresent {
		if err := r.ensureIntegrationRunnerRegistryCredsRemoved(ctx); err != nil {
			return errHandler.HandleApplyError(ctx, err)
		}
	}

	if result, err := r.syncInternalRegistryCredentialsSecret(ctx, tc); err != nil {
		return errHandler.HandleApplyError(ctx, err)
	} else if result.RequeueAfter > 0 {
		return result, nil
	}

	// Cleanup orphaned resources
	if err := tc.CleanupOrphans(ctx, constant.KonfluxOwnerLabel, defaultTenant.Name, DefaultTenantCleanupGVKs,
		tracking.WithClusterScopedAllowList(DefaultTenantClusterScopedAllowList)); err != nil {
		return errHandler.HandleCleanupError(ctx, err)
	}

	// Check the status of owned deployments and update KonfluxDefaultTenant status
	// Note: default-tenant has no deployments, so this will set Ready=true with appropriate message
	if err := condition.UpdateComponentStatuses(ctx, r.Client, defaultTenant); err != nil {
		return errHandler.HandleStatusUpdateError(ctx, err)
	}

	// Update status
	if err := r.Status().Update(ctx, defaultTenant); err != nil {
		log.Error(err, "Failed to update status")
		return ctrl.Result{}, err
	}

	log.Info("Successfully reconciled KonfluxDefaultTenant")
	return ctrl.Result{}, nil
}

// internalRegistryCRExists reports whether the KonfluxInternalRegistry singleton CR is present.
func (r *KonfluxDefaultTenantReconciler) internalRegistryCRExists(ctx context.Context) (bool, error) {
	registry := &konfluxv1alpha1.KonfluxInternalRegistry{}
	if err := r.Get(ctx, client.ObjectKey{Name: internalregistry.CRName}, registry); err != nil {
		if apierrors.IsNotFound(err) {
			return false, nil
		}
		return false, fmt.Errorf("get internal registry %q: %w", internalregistry.CRName, err)
	}
	return true, nil
}

// applyManifests loads and applies all embedded manifests to the cluster using the tracking client.
// Manifests are parsed once and cached; deep copies are used during reconciliation.
// When attachRunnerRegistryCreds is true, registry credential refs are merged into the
// konflux-integration-runner ServiceAccount object before server-side apply.
func (r *KonfluxDefaultTenantReconciler) applyManifests(ctx context.Context, tc *tracking.Client, attachRunnerRegistryCreds bool) error {
	log := logf.FromContext(ctx)

	objects, err := r.ObjectStore.GetForComponent(manifests.DefaultTenant)
	if err != nil {
		return fmt.Errorf("failed to get parsed manifests for DefaultTenant: %w", err)
	}

	for _, obj := range objects {
		if err := r.prepareIntegrationRunnerRegistryListsOnManifestSA(ctx, obj, attachRunnerRegistryCreds); err != nil {
			return err
		}
		// Apply with ownership using the tracking client
		if err := tc.ApplyOwned(ctx, obj); err != nil {
			return fmt.Errorf("failed to apply object %s/%s (%s) from %s: %w",
				obj.GetNamespace(), obj.GetName(), tracking.GetKind(obj), manifests.DefaultTenant, err)
		}
		log.V(1).Info("Applied resource",
			"kind", obj.GetObjectKind().GroupVersionKind().Kind,
			"namespace", obj.GetNamespace(),
			"name", obj.GetName(),
		)
	}
	return nil
}

// syncInternalRegistryCredentialsSecret copies registry credentials to default-tenant when
// the internal registry CR is present. If registry credentials are not available yet, it
// requeues so rotation and first-time generation are eventually propagated.
func (r *KonfluxDefaultTenantReconciler) syncInternalRegistryCredentialsSecret(
	ctx context.Context,
	tc *tracking.Client,
) (ctrl.Result, error) {
	registry := &konfluxv1alpha1.KonfluxInternalRegistry{}
	if err := r.Get(ctx, client.ObjectKey{Name: internalregistry.CRName}, registry); err != nil {
		if apierrors.IsNotFound(err) {
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, fmt.Errorf("get internal registry %q: %w", internalregistry.CRName, err)
	}

	source := &corev1.Secret{}
	if err := r.Get(ctx, client.ObjectKey{
		Namespace: RegistrySourceSecretNamespace,
		Name:      RegistrySourceSecretName,
	}, source); err != nil {
		if apierrors.IsNotFound(err) {
			return ctrl.Result{RequeueAfter: 10 * time.Second}, nil
		}
		return ctrl.Result{}, fmt.Errorf("get source secret %s/%s: %w", RegistrySourceSecretNamespace, RegistrySourceSecretName, err)
	}

	target := &corev1.Secret{}
	target.APIVersion = "v1"
	target.Kind = "Secret"
	target.SetName(RegistryCredentialsSecretName)
	target.SetNamespace(DefaultTenantNamespace)
	target.Type = source.Type
	// Keep copied secrets mutable so source credential rotations can be propagated.
	target.Immutable = nil
	target.Data = make(map[string][]byte, len(source.Data))
	for k, v := range source.Data {
		target.Data[k] = append([]byte(nil), v...)
	}
	target.StringData = nil
	if err := tc.ApplyOwned(ctx, target); err != nil {
		return ctrl.Result{}, fmt.Errorf("sync target secret %s/%s: %w", DefaultTenantNamespace, RegistryCredentialsSecretName, err)
	}

	return ctrl.Result{}, nil
}

// prepareIntegrationRunnerRegistryListsOnManifestSA merges internal-registry credential references
// into the konflux-integration-runner ServiceAccount manifest before server-side apply when the
// internal registry CR exists. It bases imagePullSecrets and secrets on the live object when
// present so other controllers' entries are preserved.
//
// Limitation: default-tenant is aimed at dev/demo-style clusters, not long-lived production
// namespaces where many independent actors manage the same ServiceAccount. Copying live list
// entries into the apply payload works with ApplyOwned's server-side apply and ForceOwnership,
// but in a heavy multi-manager scenario those fields could conflict; a dedicated design would be
// needed there.
func (r *KonfluxDefaultTenantReconciler) prepareIntegrationRunnerRegistryListsOnManifestSA(
	ctx context.Context,
	obj client.Object,
	attachRunnerRegistryCreds bool,
) error {
	if !attachRunnerRegistryCreds {
		return nil
	}

	sa, ok := obj.(*corev1.ServiceAccount)
	if !ok {
		return nil
	}
	if sa.GetNamespace() != DefaultTenantNamespace || sa.GetName() != IntegrationRunnerServiceAccountName {
		return nil
	}

	live := &corev1.ServiceAccount{}
	key := client.ObjectKey{Namespace: DefaultTenantNamespace, Name: IntegrationRunnerServiceAccountName}
	if err := r.Get(ctx, key, live); err != nil {
		if apierrors.IsNotFound(err) {
			serviceaccount.MergeSecretRefsIntoServiceAccount(sa, RegistryCredentialsSecretName)
			return nil
		}
		return fmt.Errorf("get serviceaccount %s/%s: %w", DefaultTenantNamespace, IntegrationRunnerServiceAccountName, err)
	}

	sa.ImagePullSecrets = append([]corev1.LocalObjectReference(nil), live.ImagePullSecrets...)
	sa.Secrets = append([]corev1.ObjectReference(nil), live.Secrets...)
	serviceaccount.MergeSecretRefsIntoServiceAccount(sa, RegistryCredentialsSecretName)
	return nil
}

// ensureIntegrationRunnerRegistryCredsRemoved removes RegistryCredentialsSecretName from
// konflux-integration-runner's imagePullSecrets and secrets when the KonfluxInternalRegistry CR
// is absent, so stale pull credentials are not left on the cluster. Missing ServiceAccount (get
// or patch, e.g. deleted between get and patch) is ignored. Returns an error only on unexpected
// get/patch failures.
func (r *KonfluxDefaultTenantReconciler) ensureIntegrationRunnerRegistryCredsRemoved(ctx context.Context) error {
	sa := &corev1.ServiceAccount{}
	key := client.ObjectKey{Namespace: DefaultTenantNamespace, Name: IntegrationRunnerServiceAccountName}
	if err := r.Get(ctx, key, sa); err != nil {
		if apierrors.IsNotFound(err) {
			return nil
		}
		return fmt.Errorf("get serviceaccount %s/%s: %w", DefaultTenantNamespace, IntegrationRunnerServiceAccountName, err)
	}
	original := sa.DeepCopy()
	if !serviceaccount.StripSecretRefsFromServiceAccount(sa, RegistryCredentialsSecretName) {
		return nil
	}
	if err := r.Patch(ctx, sa, client.MergeFrom(original)); err != nil {
		if apierrors.IsNotFound(err) {
			return nil
		}
		return fmt.Errorf("patch serviceaccount %s/%s to remove registry credentials: %w", DefaultTenantNamespace, IntegrationRunnerServiceAccountName, err)
	}
	return nil
}

// mapSourceSecretToDefaultTenant maps internal-registry source secret changes to the
// singleton KonfluxDefaultTenant reconcile request.
func (r *KonfluxDefaultTenantReconciler) mapSourceSecretToDefaultTenant(
	ctx context.Context,
	obj client.Object,
) []ctrl.Request {
	secret, ok := obj.(*corev1.Secret)
	if !ok {
		return nil
	}
	if secret.GetNamespace() != RegistrySourceSecretNamespace || secret.GetName() != RegistrySourceSecretName {
		return nil
	}

	dt := &konfluxv1alpha1.KonfluxDefaultTenant{}
	if err := r.Get(ctx, client.ObjectKey{Name: CRName}, dt); err != nil {
		return nil
	}
	return []ctrl.Request{{NamespacedName: client.ObjectKey{Name: CRName}}}
}

// mapInternalRegistryToDefaultTenant maps the singleton KonfluxInternalRegistry to a reconcile
// request for the KonfluxDefaultTenant CR so registry presence changes apply manifests and
// credential cleanup without waiting for resync.
func (r *KonfluxDefaultTenantReconciler) mapInternalRegistryToDefaultTenant(
	ctx context.Context,
	obj client.Object,
) []ctrl.Request {
	ir, ok := obj.(*konfluxv1alpha1.KonfluxInternalRegistry)
	if !ok {
		return nil
	}
	if ir.GetName() != internalregistry.CRName {
		return nil
	}

	dt := &konfluxv1alpha1.KonfluxDefaultTenant{}
	if err := r.Get(ctx, client.ObjectKey{Name: CRName}, dt); err != nil {
		return nil
	}
	return []ctrl.Request{{NamespacedName: client.ObjectKey{Name: CRName}}}
}

// SetupWithManager sets up the controller with the Manager.
func (r *KonfluxDefaultTenantReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&konfluxv1alpha1.KonfluxDefaultTenant{}).
		Named("konfluxdefaulttenant").
		// Watch Namespace, ServiceAccount, Secret, and RoleBindings
		Owns(&corev1.Namespace{}, builder.WithPredicates(predicate.IgnoreStatusUpdatesPredicate)).
		Owns(&corev1.Secret{}).
		Owns(&corev1.ServiceAccount{}).
		Owns(&rbacv1.RoleBinding{}).
		Watches(&konfluxv1alpha1.KonfluxInternalRegistry{},
			handler.EnqueueRequestsFromMapFunc(r.mapInternalRegistryToDefaultTenant),
			builder.WithPredicates(predicate.IgnoreStatusUpdatesPredicate),
		).
		Watches(&corev1.Secret{},
			handler.EnqueueRequestsFromMapFunc(r.mapSourceSecretToDefaultTenant),
			builder.WithPredicates(
				crpredicate.And(
					predicate.IgnoreStatusUpdatesPredicate,
					crpredicate.NewPredicateFuncs(func(o client.Object) bool {
						return o.GetNamespace() == RegistrySourceSecretNamespace && o.GetName() == RegistrySourceSecretName
					}),
				),
			)).
		Complete(r)
}
