apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tekton-chains.yaml

images:
  - name: quay.io/konflux-ci/appstudio-utils
    digest: sha256:8f4f59f1e3f71714217b113f55a40aea59f5fc63c98597b9a9b14f1c8be61a5c
