apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tekton-chains.yaml

images:
  - name: quay.io/konflux-ci/appstudio-utils
    digest: sha256:909bce0cb502caa2ff5704cfce7eb4435ec75769e6f88d2dc3ffcda8c14f4209
