apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tekton-chains.yaml

images:
  - name: quay.io/konflux-ci/appstudio-utils
    digest: sha256:131039dec81f231a6532b443f15d3d18f1c9e5959a9f01126c49a5e40d332255
