---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dex.yaml

namespace: dex

images:
  - name: registry.access.redhat.com/hi/dex
    newName: registry.access.redhat.com/hi/dex
    digest: sha256:7c762322e011b3bfcf08e753844af10cf57d8cbf9c7bb21b2cb4fef9cc2f33c6

configMapGenerator:
  - name: dex
    files:
      - config.yaml
