kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ns.yaml
  - proxy

images:
  # workspace-manager
  - name: quay.io/konflux-ci/workspace-manager
    digest: sha256:d72968158bec10442236d4f84a904beeff5a022f3e032ecdd2d421651c01f8d3
  - name: quay.io/konflux-ci/konflux-ui
    digest: sha256:270f53c0b6e86dc790d78217f2101ff18a6b670e3973c97a926eefaec901c039

namespace: konflux-ui
