kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ns.yaml
  - proxy

images:
  # workspace-manager
  - name: quay.io/konflux-ci/workspace-manager
    digest: sha256:d72968158bec10442236d4f84a904beeff5a022f3e032ecdd2d421651c01f8d3
  - name: quay.io/konflux-ci/konflux-ui
    digest: sha256:7f57384b63714be3ea9f4062e88aaf1ba1c2178b8d77f1490fd1b9b54c9d8343

namespace: konflux-ui
