apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/conforma/crds/config/crd?ref=6f685d079f1991c801d39d011b74ffa9c1fb09e3
  - ns.yaml
  - configmap-viewer-role.yaml
  - public-ecp-rbac.yaml

namespace: enterprise-contract-service

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/conforma/tekton-task:latest@sha256:564e6936eaa08b027f9105b768b24c239b88897a4f0b01d520db7f9e901aee90
      - verify_ec_task_git_url=https://github.com/conforma/cli.git
      - verify_ec_task_git_revision=8e9b3585892930a91ff284824ff1c4a40e6d5e29
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml

patches:
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleYAMLSample
      name: ecp-example
    path: remove-ecp-example.yaml
