apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/conforma/crds/config/crd?ref=6f685d079f1991c801d39d011b74ffa9c1fb09e3
  - ns.yaml
  - configmap-viewer-role.yaml
  - public-ecp-rbac.yaml

namespace: enterprise-contract-service

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/conforma/tekton-task:latest@sha256:4caf88635118d46e2828a796a7073daa2a715a673637e8721ff11769fcad02b7
      - verify_ec_task_git_url=https://github.com/conforma/cli.git
      - verify_ec_task_git_revision=1026da746d2717e25c0adac582f2d37694b0bd84
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml

patches:
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleYAMLSample
      name: ecp-example
    path: remove-ecp-example.yaml
