apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/conforma/crds/config/crd?ref=fde949e2227b9be547e3435ccbe4b496a86176c5
  - ns.yaml
  - configmap-viewer-role.yaml
  - public-ecp-rbac.yaml

namespace: enterprise-contract-service

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/conforma/tekton-task:latest@sha256:dbb691e67404f90058a055f3ed0cc505214f6fd2bf292f41db92911738a150d0
      - verify_ec_task_git_url=https://github.com/conforma/cli.git
      - verify_ec_task_git_revision=047e1aef6b58305e72ad61faf1241498f297f247
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
      - verify_conforma_task_ta_git_pathInRepo=tasks/verify-conforma-konflux-ta/0.1/verify-conforma-konflux-ta.yaml

patches:
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleYAMLSample
      name: ecp-example
    path: remove-ecp-example.yaml
