apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: konflux-cli

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - rbac.yaml

configMapGenerator:
  - name: create-tenant
    files:
      - create-tenant.sh
  - name: setup-release
    files:
      - setup-release.sh
