apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml

images:
  - name: quay.io/konflux-ci/appstudio-utils
    digest: sha256:3014a613a4aafb198f4515aca05a91603de45739ad70509020bca9ef05b6e91b
