apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml

images:
  - name: quay.io/konflux-ci/appstudio-utils
    digest: sha256:8fb2d2869be712455de743acc556aa8717154509019906c45c30b513cb94d8a2
