apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml

images:
  - name: quay.io/konflux-ci/appstudio-utils
    digest: sha256:311552b4c9897976c4ffa112ee1444fa1bba0721e613906e64a7a08c56cb4854
