apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- rbac.yaml
- service.yaml
- certificate.yaml
- network_policy_allow_to_apiserver.yaml
- network_policy_allow_from_konfluxui.yaml
- deny-virtual-domain.yaml
namespace: namespace-lister
images:
- digest: sha256:ff560d58a878777bbfd30fe4a69cba053afa17a0d5008dae85ade76a4ca76b9c
  name: quay.io/konflux-ci/namespace-lister
  newName: quay.io/konflux-ci/namespace-lister
patches:
# Prevent deployment failures during slow dependency setup
- target:
    group: apps
    version: v1
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 2147483647
- path: ./patches/with_header_auth_user.yaml
  target:
    group: apps
    kind: Deployment
    name: namespace-lister
    namespace: namespace-lister
- path: ./patches/with_header_auth_groups.yaml
  target:
    group: apps
    kind: Deployment
    name: namespace-lister
    namespace: namespace-lister
