apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- rbac.yaml
- service.yaml
- certificate.yaml
- network_policy_allow_to_apiserver.yaml
- network_policy_allow_from_konfluxui.yaml
namespace: namespace-lister
images:
- digest: sha256:990e0ad159168851beed23ecc32bc3b66983729167768b8b7d3e77fc12df0a42
  name: quay.io/konflux-ci/namespace-lister
  newName: quay.io/konflux-ci/namespace-lister
patches:
# Prevent deployment failures during slow dependency setup
- target:
    group: apps
    version: v1
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 2147483647
