apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- rbac.yaml
- service.yaml
- certificate.yaml
- network_policy_allow_to_apiserver.yaml
- network_policy_allow_from_konfluxui.yaml
namespace: namespace-lister
images:
- digest: sha256:a76767fc9be4d75d920e4c430f3e6818a8897f4266908fdf086040d1d8740d73
  name: quay.io/konflux-ci/namespace-lister
  newName: quay.io/konflux-ci/namespace-lister
patches:
# Prevent deployment failures during slow dependency setup
- target:
    group: apps
    version: v1
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 2147483647
- path: ./patches/with_header_auth_user.yaml
  target:
    group: apps
    kind: Deployment
    name: namespace-lister
    namespace: namespace-lister
- path: ./patches/with_header_auth_groups.yaml
  target:
    group: apps
    kind: Deployment
    name: namespace-lister
    namespace: namespace-lister
