apiVersion: v1
kind: ConfigMap
metadata:
  name: release-service-manager-config
  namespace: release-service
  labels:
  {{- include "release.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: {{ .Values.releaseServiceManagerConfig.controllerManagerConfigYaml
    | toYaml | indent 1 }}
