apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cluster-issuer
  - keycloak
  - pipelines-as-code
  - pre-deployment-pvc-binding
  - tekton-config
  - tekton-operator
  - tekton-results
