apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:d7ea3bcfbd51cf6db3c7bd8620fadbb2a73d4e238c467c34abf3ca9e4790de9f
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:e0347e0187000a022e7ce2088f74f772251481c31e60937a7d11e157809f973b
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:f67848cb58c0bfa4ef9162d2ac3d208d44f6f3a09d04449fd8700d1cdc0b5074
