apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: redhat-trusted-tasks
  namespace: enterprise-contract-service
spec:
  description: Rules used to verify Tekton Task definitions comply to Red Hat's standards.
  name: Red Hat Trusted Tasks
  sources:
  - config:
      exclude: []
      include:
      - kind
    data:
    - github.com/release-engineering/rhtap-ec-policy.git//data?ref=acaef210b5ddca7a87854b5141556c30efdc2afc
    name: Default
    policy:
    - oci::quay.io/conforma/task-policy:konflux@sha256:bcd7394c39e87fe0934f92d3260df39739a2890ac90393b459de04549d1a3161
