apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: redhat-no-hermetic
  namespace: enterprise-contract-service
spec:
  description: Includes most of the rules and policies required internally by Red
    Hat when building Red Hat products. It excludes the requirement of hermetic builds.
    Available collections are defined in https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/release_policy.html#_available_rule_collections.
    If a different policy configuration is desired, this resource can serve as a starting
    point. See the docs on how to include and exclude rules https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/policy_configuration.html#_including_and_excluding_rules.
  name: Red Hat (non hermetic)
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - config:
      exclude:
      - hermetic_build_task
      - tasks.required_tasks_found:prefetch-dependencies
      include:
      - '@redhat'
    data:
    - oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest@sha256:0affee8ccc186d69e31deb44106c1d6a0aac5774408935025033db7c1a5e8dd9
    - github.com/release-engineering/rhtap-ec-policy.git//data?ref=dd1a3dd1bf2299e1da9936b89e7279b6ab443bec
    name: Default
    policy:
    - oci::quay.io/conforma/release-policy:konflux@sha256:6eb386faaf76de0d7dbc9f9e770a7f5639ebcee88e4ed4f004f8053189b21eae
