apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: default
  namespace: enterprise-contract-service
spec:
  description: Includes most of the rules and policies required internally by Red
    Hat when building Red Hat products. It excludes the requirement of hermetic builds.
    Available collections are defined in https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/release_policy.html#_available_rule_collections.
    If a different policy configuration is desired, this resource can serve as a starting
    point. See the docs on how to include and exclude rules https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/policy_configuration.html#_including_and_excluding_rules.
  name: Default
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - config:
      exclude:
        # Hermetic builds are great, but there is usually a significant amount of work to make
        # them work which can be intimidating during the onboarding process.
        - hermetic_task
        # Konflux supports packaging the source code used for building an image to be packaged
        # as an OCI artifact attached to the image. Although this is great for open source, it
        # can catch users by surprise and potentially leak code that is not meant to be open.
        - source_image
        # Konflux, via Hermeto, has support for the experimental RPM lockfiles. When that is used
        # this policy package ensures that the RPMs listed in the SBOM declare which YUM/DNF repo
        # they came from. This is important for mapping CVEs to RPMs during content analysis
        # performed by clair.
        # NOTE: To enable this policy package, the full list of RPM repositories has to be provided
        # as rule data. Red Hat provides this list here:
        # https://github.com/release-engineering/rhtap-ec-policy/blob/main/data/known_rpm_repositories.yml
        # However, it is not possible to include just that file in the rule data.
        - rpm_repos
      include:
      - '@redhat'
    data:
    - oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest@sha256:55df485d2e13c93bafe4440254306ea00508c02ca2f18b774212a793c7d235db
    - github.com/redhat-appstudio/tsf-conforma-data//data?ref=1966f21842d507441a7a5e1c7de9071cf3f9ec53
    name: Default
    policy:
    - oci::quay.io/conforma/release-policy:konflux@sha256:1b296a925b4021f4b4959ea289596925a8735540e554f3ba7754a651731a216f
