apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_default.yaml

namespace: enterprise-contract-service
