apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-services/config/crd?ref=ef7255ae8f0834b7cdd820e907ed6842f22c71e6

namespace: release-service
