apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-services/config/crd?ref=2f3a79d47ede66547121c2ad61d45c0838d79478

namespace: release-service
