apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    kubernetes.io/service-account.name: integration-service-metrics-reader
  name: integration-service-metrics-reader
  namespace: integration-service
type: kubernetes.io/service-account-token
