apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta-min
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:952cd5147c6135167fbad7fada90ef6bcbfd9767c57d2d92663d035b83144901
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:fb2c77014ad4983770ae5faf890ee6f0aa58fe2ee019d8d0fe051718effd0328
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:4194844179cd4db44faba402355f23dabbb083437b0b7ec08adce494d3a6844e
    - name: tekton-bundle-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder@sha256:0409ff46239e41e04ee13eb1e584a58ad53fb0922c66eb85e59f0a8d887cfe93
    - name: tekton-bundle-builder-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder-oci-ta@sha256:0e322b4073a32bbd04166c84c83f2369f39356fce22007f83d5245a086754808
    - name: docker-build-oci-ta-min
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta-min@sha256:32ad438b25955382666494e5bb15bf666c7fc8ac7413d3ae26597876284637b9
      description: minimal version of the docker-build-oci-ta pipeline, which requires less compute resources. In addition, it doesn't contain tasks which require user provided secrets.
