apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - v1_serviceaccount_release-service-metrics-reader.yaml
  - v1_secret_release-service-metrics-reader.yaml
  - rbac.authorization.k8s.io_v1_clusterrole_release-service-metrics-reader.yaml
  - rbac.authorization.k8s.io_v1_clusterrolebinding_prometheus-release-service-metrics-reader.yaml
  - monitoring.coreos.com_v1_servicemonitor_release-service.yaml
