apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-service
  namespace: release-service
spec:
  endpoints:
  - bearerTokenSecret:
      key: token
      name: release-service-metrics-reader
    interval: 15s
    path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      control-plane: controller-manager
