apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-release-service-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-service-metrics-reader
subjects:
- kind: ServiceAccount
  name: release-service-metrics-reader
  namespace: release-service
