apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dex.yaml

images:
  - name: quay.io/konflux-ci/dex
    newName: quay.io/konflux-ci/dex
    digest: sha256:85b5ab8471555be4111eea2a162e3a3d9e141dc42709d93e589e96e0b77a127d

configMapGenerator:
- files:
  - run-dex.sh
  name: run-dex
  options:
    disableNameSuffixHash: false
