apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dex.yaml

images:
  - name: quay.io/konflux-ci/dex
    newName: quay.io/konflux-ci/dex
    digest: sha256:f8d7a917e36e1f4cb5b11f4e4a448d2784d3cf3737fe6df0dc2245ff0da76edb

configMapGenerator:
- files:
  - run-dex.sh
  name: run-dex
  options:
    disableNameSuffixHash: false
