apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dex.yaml

images:
  - name: quay.io/konflux-ci/dex
    newName: quay.io/konflux-ci/dex
    digest: sha256:0c87b64aa0aab8720415457ebce15ca4a69ab3387603f4b65384521d4a7a7046

configMapGenerator:
- files:
  - run-dex.sh
  name: run-dex
  options:
    disableNameSuffixHash: false
