---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - certificate.yaml
  - quay.yaml
images:
  - name: quay.io/projectquay/quay
    newTag: "v3.17.3"
  - name: quay.io/sclorg/postgresql-15-c9s
    newTag: "20260708"
  - name: quay.io/sclorg/redis-7-c9s
    newTag: "20250108"
