---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - registry.yaml
  - certificate.yaml
  - trust-bundle.yaml
  - zot-config.yaml

images:
  - name: quay.io/konflux-ci/zot
    newName: quay.io/konflux-ci/zot
    digest: sha256:a5adb13fc49106d575cf9d1e27114a13e48bdeb1b9081e35c38b26ea00025f36
