---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - registry.yaml
  - certificate.yaml
  - trust-bundle.yaml
  - zot-config.yaml

images:
  - name: quay.io/konflux-ci/zot
    newName: quay.io/konflux-ci/zot
    digest: sha256:343fcec4406863a44a6d9a286da622f7675af259b2a056f85c6de0d5e96355cc
