---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - registry.yaml
  - certificate.yaml
  - trust-bundle.yaml
  - zot-config.yaml

images:
  - name: quay.io/konflux-ci/zot
    newName: quay.io/konflux-ci/zot
    digest: sha256:fec7a84e9865b6f86b1f44af5baadf4525ec75488409b16fef372398f2fd8e40
