---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - smee-client.yaml

images:
  - name: ghcr.io/chmouel/gosmee
    newName: ghcr.io/chmouel/gosmee
    newTag: v0.32.0
  - name: quay.io/konflux-ci/smee-sidecar
    newName: quay.io/konflux-ci/smee-sidecar
    newTag: latest@sha256:ebd206f7a4c606a0172ba0c0f4eaab15fcfce1fcff707a1d8b3036e7a168cb9f

patches:
  - path: smee-channel-id.yaml
    target:
      kind: Deployment
      name: gosmee-client
