---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - smee-client.yaml

images:
  - name: ghcr.io/chmouel/gosmee
    newName: ghcr.io/chmouel/gosmee
    newTag: v0.29.0
  - name: quay.io/konflux-ci/smee-sidecar
    newName: quay.io/konflux-ci/smee-sidecar
    newTag: latest@sha256:c9a4abcd800dcce9e3bef68e1f8dc133f6619d51e7e37c5f7392efad46ed7e6e

patches:
  - path: smee-channel-id.yaml
    target:
      kind: Deployment
      name: gosmee-client
