---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - smee-client.yaml

images:
  - name: ghcr.io/chmouel/gosmee
    newName: ghcr.io/chmouel/gosmee
    newTag: v0.32.0
  - name: quay.io/konflux-ci/smee-sidecar
    newName: quay.io/konflux-ci/smee-sidecar
    newTag: latest@sha256:828dd317b6f03ea11b839fd44c6dd82faf0582acab4b33e2e775ad36c752efa0

patches:
  - path: smee-channel-id.yaml
    target:
      kind: Deployment
      name: gosmee-client
