name: Static code checks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:
    types: [checks_requested]

jobs:
  kube-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7
        with:
          go-version-file: operator/go.mod
          cache-dependency-path: operator/go.sum
      - name: Run kube-linter
        run: ./.github/scripts/run-kube-linter.sh
